# Generated by Django 2.2 on 2019-12-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
