# Generated by Django 2.2 on 2020-01-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_extendeduser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
